apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: "${SERVICE_NAME}"
  labels:
    cloud.googleapis.com/location: "${REGION}"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/network-interfaces: '[{"network":"${VPC_NETWORK}","subnetwork":"${VPC_SUBNET}","tags":["${NETWORK_TAG}"]}]'
        # run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      containerConcurrency: 80
      containers:
      - image: "${CONTAINER_IMAGE}"
  traffic:
  - percent: 100
    latestRevision: true
