name: Build and Deploy React App

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-prod:
    uses: ./.github/workflows/build_push_template.yml
    with:
      environment: production
      tag: ${{ github.sha }}
    secrets:
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      VPC_NETWORK: ${{ secrets.VPC_NETWORK }}
      VPC_SUBNET: ${{ secrets.VPC_SUBNET }}
      NETWORK_TAG: ${{ secrets.NETWORK_TAG }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

